


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
begin
    insert into public.profiles (
        id,
        full_name,
        email,
        avatar_url,
        role
    )
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'full_name',
            new.raw_user_meta_data ->> 'name'
        ),
        new.email,
        new.raw_user_meta_data ->> 'avatar_url',
        'Sales'
    )
    on conflict (id) do nothing;

    return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
    select exists (
        select 1
        from public.profiles
        where id = auth.uid()
          and role = 'Administrator'
          and is_active = true
    );
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."set_activity_log_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO 'public'
    AS $$
DECLARE
  v_email TEXT;
  v_name TEXT;
BEGIN
  -- Always use the actual logged-in user
  NEW.user_id := auth.uid();

  -- Get email directly from auth.users
  SELECT email
  INTO v_email
  FROM auth.users
  WHERE id = auth.uid();

  -- Try common Google/Auth profile name fields
  SELECT COALESCE(
    raw_user_meta_data->>'full_name',
    raw_user_meta_data->>'name',
    raw_user_meta_data->>'display_name'
  )
  INTO v_name
  FROM auth.users
  WHERE id = auth.uid();

  -- Store user details
  NEW.user_email := COALESCE(v_email, '');

  NEW.user_name := COALESCE(
    NULLIF(v_name, ''),
    NULLIF(v_email, ''),
    'Unknown User'
  );

  RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."set_activity_log_user"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."activity_logs" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "user_name" "text",
    "user_email" "text",
    "action" "text" NOT NULL,
    "module" "text" NOT NULL,
    "record_id" "text",
    "record_name" "text",
    "description" "text",
    "old_data" "jsonb",
    "new_data" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE ONLY "public"."activity_logs" REPLICA IDENTITY FULL;


ALTER TABLE "public"."activity_logs" OWNER TO "postgres";


ALTER TABLE "public"."activity_logs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."activity_logs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."clients" (
    "id" bigint NOT NULL,
    "company_name" "text" NOT NULL,
    "contact_person" "text",
    "phone" "text",
    "email" "text",
    "alternate_phone" "text",
    "address" "text",
    "city" "text",
    "state" "text",
    "pincode" "text",
    "business_type" "text",
    "gst_number" "text",
    "website" "text",
    "assigned_to_id" bigint,
    "status" "text" DEFAULT 'Active'::"text" NOT NULL,
    "client_since" "date",
    "notes" "text",
    "internal_notes" "text",
    "is_archived" boolean DEFAULT false NOT NULL,
    "archived_at" timestamp with time zone,
    "archived_by" "uuid",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "Name: crm_client_id" "text",
    "crm_client_id" "text"
);


ALTER TABLE "public"."clients" OWNER TO "postgres";


ALTER TABLE "public"."clients" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."clients_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."follow_ups" (
    "id" bigint NOT NULL,
    "lead_id" bigint,
    "client_id" bigint,
    "assigned_to_id" bigint,
    "follow_up_date" "date" NOT NULL,
    "follow_up_time" time without time zone,
    "type" "text" DEFAULT 'Call'::"text" NOT NULL,
    "subject" "text",
    "notes" "text",
    "outcome" "text",
    "next_action" "text",
    "next_follow_up_date" "date",
    "status" "text" DEFAULT 'Open'::"text" NOT NULL,
    "priority" "text" DEFAULT 'Medium'::"text" NOT NULL,
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "completed_at" timestamp with time zone
);


ALTER TABLE "public"."follow_ups" OWNER TO "postgres";


ALTER TABLE "public"."follow_ups" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."follow_ups_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."invoice_items" (
    "id" bigint NOT NULL,
    "invoice_id" bigint NOT NULL,
    "service_id" bigint,
    "description" "text" NOT NULL,
    "quantity" numeric(12,2) DEFAULT 1 NOT NULL,
    "unit_price" numeric(12,2) DEFAULT 0 NOT NULL,
    "amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."invoice_items" OWNER TO "postgres";


ALTER TABLE "public"."invoice_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."invoice_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."invoices" (
    "id" bigint NOT NULL,
    "invoice_number" "text" NOT NULL,
    "client_id" bigint NOT NULL,
    "quotation_id" bigint,
    "invoice_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "due_date" "date",
    "sales_person_id" bigint,
    "subtotal" numeric(12,2) DEFAULT 0 NOT NULL,
    "discount" numeric(12,2) DEFAULT 0 NOT NULL,
    "tax_percent" numeric(5,2) DEFAULT 0 NOT NULL,
    "tax_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "total_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "amount_paid" numeric(12,2) DEFAULT 0 NOT NULL,
    "balance_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "status" "text" DEFAULT 'Unpaid'::"text" NOT NULL,
    "notes" "text",
    "terms_conditions" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "items" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "renewal_id" bigint,
    "renewal_reference" "text"
);


ALTER TABLE "public"."invoices" OWNER TO "postgres";


ALTER TABLE "public"."invoices" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."invoices_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."leads" (
    "id" bigint NOT NULL,
    "company_name" "text" NOT NULL,
    "contact_person" "text",
    "phone" "text",
    "email" "text",
    "address" "text",
    "lead_source" "text",
    "source_details" "text",
    "assigned_to_id" bigint,
    "interested_service_id" bigint,
    "interested_service" "text",
    "requirement" "text",
    "expected_value" numeric(12,2),
    "expected_closing_date" "date",
    "commission_applicable" boolean DEFAULT false NOT NULL,
    "commission_percent" numeric(5,2),
    "commission_amount" numeric(12,2),
    "commission_status" "text",
    "commission_paid_date" "date",
    "reference_person_name" "text",
    "reference_person_phone" "text",
    "reference_person_email" "text",
    "next_follow_up_date" "date",
    "next_follow_up_time" time without time zone,
    "next_action" "text",
    "notes" "text",
    "internal_notes" "text",
    "lost_reason" "text",
    "status" "text" DEFAULT 'New'::"text" NOT NULL,
    "priority" "text" DEFAULT 'Medium'::"text" NOT NULL,
    "created_by" "uuid",
    "converted_at" timestamp with time zone,
    "converted_client_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "follow_up_assigned_to_id" bigint
);


ALTER TABLE "public"."leads" OWNER TO "postgres";


ALTER TABLE "public"."leads" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."leads_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."payments" (
    "id" bigint NOT NULL,
    "invoice_id" bigint NOT NULL,
    "client_id" bigint NOT NULL,
    "payment_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "amount" numeric(12,2) NOT NULL,
    "payment_method" "text" DEFAULT 'Bank Transfer'::"text" NOT NULL,
    "transaction_reference" "text",
    "status" "text" DEFAULT 'Received'::"text" NOT NULL,
    "notes" "text",
    "received_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."payments" OWNER TO "postgres";


ALTER TABLE "public"."payments" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."payments_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "full_name" "text",
    "email" "text",
    "avatar_url" "text",
    "role" "text" DEFAULT 'Sales'::"text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "profiles_role_check" CHECK (("role" = ANY (ARRAY['Administrator'::"text", 'Sales'::"text", 'Accounts'::"text", 'Operations'::"text"])))
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."quotation_items" (
    "id" bigint NOT NULL,
    "quotation_id" bigint NOT NULL,
    "service_id" bigint,
    "description" "text" NOT NULL,
    "quantity" numeric(12,2) DEFAULT 1 NOT NULL,
    "unit_price" numeric(12,2) DEFAULT 0 NOT NULL,
    "amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."quotation_items" OWNER TO "postgres";


ALTER TABLE "public"."quotation_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."quotation_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."quotations" (
    "id" bigint NOT NULL,
    "quotation_number" "text" NOT NULL,
    "client_id" bigint,
    "lead_id" bigint,
    "quotation_date" "date" DEFAULT CURRENT_DATE NOT NULL,
    "valid_until" "date",
    "sales_person_id" bigint,
    "subtotal" numeric(12,2) DEFAULT 0 NOT NULL,
    "discount" numeric(12,2) DEFAULT 0 NOT NULL,
    "tax_percent" numeric(5,2) DEFAULT 0 NOT NULL,
    "tax_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "total_amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "status" "text" DEFAULT 'Draft'::"text" NOT NULL,
    "notes" "text",
    "terms_conditions" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "items" "jsonb" DEFAULT '[]'::"jsonb" NOT NULL,
    "scope_of_work" "text",
    "implementation_process" "text",
    "support_training" "text",
    "remarks" "text"
);


ALTER TABLE "public"."quotations" OWNER TO "postgres";


ALTER TABLE "public"."quotations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."quotations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."renewals" (
    "id" bigint NOT NULL,
    "client_id" bigint NOT NULL,
    "service_id" bigint,
    "service_name" "text",
    "renewal_date" "date" NOT NULL,
    "amount" numeric(12,2) DEFAULT 0 NOT NULL,
    "status" "text" DEFAULT 'Upcoming'::"text" NOT NULL,
    "priority" "text" DEFAULT 'Medium'::"text" NOT NULL,
    "reminder_date" "date",
    "reminder_sent" boolean DEFAULT false NOT NULL,
    "assigned_to_id" bigint,
    "notes" "text",
    "created_by" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "is_archived" boolean DEFAULT false NOT NULL,
    "completed_at" timestamp with time zone
);


ALTER TABLE "public"."renewals" OWNER TO "postgres";


ALTER TABLE "public"."renewals" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."renewals_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."sales_persons" (
    "id" bigint NOT NULL,
    "profile_id" "uuid",
    "name" "text" NOT NULL,
    "email" "text",
    "mobile" "text",
    "type" "text" DEFAULT 'Staff'::"text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "commission_percent" numeric(5,2) DEFAULT 0 NOT NULL,
    "notes" "text",
    CONSTRAINT "sales_persons_type_check" CHECK (("type" = ANY (ARRAY['Staff'::"text", 'Part-time'::"text", 'External'::"text"])))
);


ALTER TABLE "public"."sales_persons" OWNER TO "postgres";


ALTER TABLE "public"."sales_persons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."sales_persons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."services" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "default_price" numeric(12,2),
    "billing_type" "text" DEFAULT 'One Time'::"text" NOT NULL,
    "is_active" boolean DEFAULT true NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category" "text",
    "sac_code" "text",
    "gst_percent" numeric(5,2) DEFAULT 18,
    "notes" "text",
    "service_code" "text",
    CONSTRAINT "services_billing_type_check" CHECK (("billing_type" = ANY (ARRAY['One Time'::"text", 'Monthly'::"text", 'Yearly'::"text", 'As Required'::"text"])))
);


ALTER TABLE "public"."services" OWNER TO "postgres";


ALTER TABLE "public"."services" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."services_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."activity_logs"
    ADD CONSTRAINT "activity_logs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."follow_ups"
    ADD CONSTRAINT "follow_ups_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."invoice_items"
    ADD CONSTRAINT "invoice_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_invoice_number_key" UNIQUE ("invoice_number");



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quotation_items"
    ADD CONSTRAINT "quotation_items_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quotations"
    ADD CONSTRAINT "quotations_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."quotations"
    ADD CONSTRAINT "quotations_quotation_number_key" UNIQUE ("quotation_number");



ALTER TABLE ONLY "public"."renewals"
    ADD CONSTRAINT "renewals_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."sales_persons"
    ADD CONSTRAINT "sales_persons_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."services"
    ADD CONSTRAINT "services_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."services"
    ADD CONSTRAINT "services_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_activity_logs_action" ON "public"."activity_logs" USING "btree" ("action");



CREATE INDEX "idx_activity_logs_created_at" ON "public"."activity_logs" USING "btree" ("created_at" DESC);



CREATE INDEX "idx_activity_logs_module" ON "public"."activity_logs" USING "btree" ("module");



CREATE INDEX "idx_activity_logs_user_id" ON "public"."activity_logs" USING "btree" ("user_id");



CREATE INDEX "idx_clients_archived" ON "public"."clients" USING "btree" ("is_archived");



CREATE INDEX "idx_clients_assigned_to" ON "public"."clients" USING "btree" ("assigned_to_id");



CREATE INDEX "idx_clients_company_name" ON "public"."clients" USING "btree" ("company_name");



CREATE INDEX "idx_clients_created_at" ON "public"."clients" USING "btree" ("created_at");



CREATE INDEX "idx_clients_phone" ON "public"."clients" USING "btree" ("phone");



CREATE INDEX "idx_clients_status" ON "public"."clients" USING "btree" ("status");



CREATE INDEX "idx_follow_ups_assigned_to" ON "public"."follow_ups" USING "btree" ("assigned_to_id");



CREATE INDEX "idx_follow_ups_client" ON "public"."follow_ups" USING "btree" ("client_id");



CREATE INDEX "idx_follow_ups_date" ON "public"."follow_ups" USING "btree" ("follow_up_date");



CREATE INDEX "idx_follow_ups_lead" ON "public"."follow_ups" USING "btree" ("lead_id");



CREATE INDEX "idx_follow_ups_status" ON "public"."follow_ups" USING "btree" ("status");



CREATE INDEX "idx_invoice_items_invoice" ON "public"."invoice_items" USING "btree" ("invoice_id");



CREATE INDEX "idx_invoices_client" ON "public"."invoices" USING "btree" ("client_id");



CREATE INDEX "idx_invoices_date" ON "public"."invoices" USING "btree" ("invoice_date");



CREATE INDEX "idx_invoices_due_date" ON "public"."invoices" USING "btree" ("due_date");



CREATE INDEX "idx_invoices_quotation" ON "public"."invoices" USING "btree" ("quotation_id");



CREATE INDEX "idx_invoices_sales_person" ON "public"."invoices" USING "btree" ("sales_person_id");



CREATE INDEX "idx_invoices_status" ON "public"."invoices" USING "btree" ("status");



CREATE INDEX "idx_leads_assigned_to" ON "public"."leads" USING "btree" ("assigned_to_id");



CREATE INDEX "idx_leads_created_at" ON "public"."leads" USING "btree" ("created_at");



CREATE INDEX "idx_leads_follow_up" ON "public"."leads" USING "btree" ("next_follow_up_date");



CREATE INDEX "idx_leads_phone" ON "public"."leads" USING "btree" ("phone");



CREATE INDEX "idx_leads_priority" ON "public"."leads" USING "btree" ("priority");



CREATE INDEX "idx_leads_status" ON "public"."leads" USING "btree" ("status");



CREATE INDEX "idx_payments_client" ON "public"."payments" USING "btree" ("client_id");



CREATE INDEX "idx_payments_date" ON "public"."payments" USING "btree" ("payment_date");



CREATE INDEX "idx_payments_invoice" ON "public"."payments" USING "btree" ("invoice_id");



CREATE INDEX "idx_payments_status" ON "public"."payments" USING "btree" ("status");



CREATE INDEX "idx_quotation_items_quotation" ON "public"."quotation_items" USING "btree" ("quotation_id");



CREATE INDEX "idx_quotations_client" ON "public"."quotations" USING "btree" ("client_id");



CREATE INDEX "idx_quotations_date" ON "public"."quotations" USING "btree" ("quotation_date");



CREATE INDEX "idx_quotations_lead" ON "public"."quotations" USING "btree" ("lead_id");



CREATE INDEX "idx_quotations_sales_person" ON "public"."quotations" USING "btree" ("sales_person_id");



CREATE INDEX "idx_quotations_status" ON "public"."quotations" USING "btree" ("status");



CREATE INDEX "idx_renewals_assigned_to" ON "public"."renewals" USING "btree" ("assigned_to_id");



CREATE INDEX "idx_renewals_client" ON "public"."renewals" USING "btree" ("client_id");



CREATE INDEX "idx_renewals_date" ON "public"."renewals" USING "btree" ("renewal_date");



CREATE INDEX "idx_renewals_service" ON "public"."renewals" USING "btree" ("service_id");



CREATE INDEX "idx_renewals_status" ON "public"."renewals" USING "btree" ("status");



CREATE INDEX "idx_sales_persons_active" ON "public"."sales_persons" USING "btree" ("is_active");



CREATE INDEX "idx_sales_persons_profile_id" ON "public"."sales_persons" USING "btree" ("profile_id");



CREATE INDEX "idx_services_active" ON "public"."services" USING "btree" ("is_active");



CREATE INDEX "idx_services_category" ON "public"."services" USING "btree" ("category");



CREATE UNIQUE INDEX "idx_services_service_code" ON "public"."services" USING "btree" ("service_code");



CREATE OR REPLACE TRIGGER "trg_activity_log_user" BEFORE INSERT ON "public"."activity_logs" FOR EACH ROW EXECUTE FUNCTION "public"."set_activity_log_user"();



ALTER TABLE ONLY "public"."activity_logs"
    ADD CONSTRAINT "activity_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_archived_by_fkey" FOREIGN KEY ("archived_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_assigned_to_id_fkey" FOREIGN KEY ("assigned_to_id") REFERENCES "public"."sales_persons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."clients"
    ADD CONSTRAINT "clients_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "fk_leads_converted_client" FOREIGN KEY ("converted_client_id") REFERENCES "public"."clients"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."follow_ups"
    ADD CONSTRAINT "follow_ups_assigned_to_id_fkey" FOREIGN KEY ("assigned_to_id") REFERENCES "public"."sales_persons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."follow_ups"
    ADD CONSTRAINT "follow_ups_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."follow_ups"
    ADD CONSTRAINT "follow_ups_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."follow_ups"
    ADD CONSTRAINT "follow_ups_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."invoice_items"
    ADD CONSTRAINT "invoice_items_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."invoice_items"
    ADD CONSTRAINT "invoice_items_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_quotation_id_fkey" FOREIGN KEY ("quotation_id") REFERENCES "public"."quotations"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_renewal_id_fkey" FOREIGN KEY ("renewal_id") REFERENCES "public"."renewals"("id");



ALTER TABLE ONLY "public"."invoices"
    ADD CONSTRAINT "invoices_sales_person_id_fkey" FOREIGN KEY ("sales_person_id") REFERENCES "public"."sales_persons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_assigned_to_id_fkey" FOREIGN KEY ("assigned_to_id") REFERENCES "public"."sales_persons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_follow_up_assigned_to_id_fkey" FOREIGN KEY ("follow_up_assigned_to_id") REFERENCES "public"."sales_persons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."leads"
    ADD CONSTRAINT "leads_interested_service_id_fkey" FOREIGN KEY ("interested_service_id") REFERENCES "public"."services"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."payments"
    ADD CONSTRAINT "payments_received_by_fkey" FOREIGN KEY ("received_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quotation_items"
    ADD CONSTRAINT "quotation_items_quotation_id_fkey" FOREIGN KEY ("quotation_id") REFERENCES "public"."quotations"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."quotation_items"
    ADD CONSTRAINT "quotation_items_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."quotations"
    ADD CONSTRAINT "quotations_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."quotations"
    ADD CONSTRAINT "quotations_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."quotations"
    ADD CONSTRAINT "quotations_lead_id_fkey" FOREIGN KEY ("lead_id") REFERENCES "public"."leads"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."quotations"
    ADD CONSTRAINT "quotations_sales_person_id_fkey" FOREIGN KEY ("sales_person_id") REFERENCES "public"."sales_persons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."renewals"
    ADD CONSTRAINT "renewals_assigned_to_id_fkey" FOREIGN KEY ("assigned_to_id") REFERENCES "public"."sales_persons"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."renewals"
    ADD CONSTRAINT "renewals_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE RESTRICT;



ALTER TABLE ONLY "public"."renewals"
    ADD CONSTRAINT "renewals_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."renewals"
    ADD CONSTRAINT "renewals_service_id_fkey" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."sales_persons"
    ADD CONSTRAINT "sales_persons_profile_id_fkey" FOREIGN KEY ("profile_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



CREATE POLICY "Admins can view activity logs" ON "public"."activity_logs" FOR SELECT TO "authenticated" USING ("public"."is_admin"());



CREATE POLICY "Authenticated users can create activity logs" ON "public"."activity_logs" FOR INSERT TO "authenticated" WITH CHECK (("user_id" = "auth"."uid"()));



ALTER TABLE "public"."activity_logs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."clients" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "clients_insert_authenticated" ON "public"."clients" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "clients_select_authenticated" ON "public"."clients" FOR SELECT TO "authenticated" USING ((("is_archived" = false) OR "public"."is_admin"()));



CREATE POLICY "clients_update_authenticated" ON "public"."clients" FOR UPDATE TO "authenticated" USING ((("is_archived" = false) OR "public"."is_admin"())) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."follow_ups" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "follow_ups_insert_authenticated" ON "public"."follow_ups" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "follow_ups_select_authenticated" ON "public"."follow_ups" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "follow_ups_update_authenticated" ON "public"."follow_ups" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."invoice_items" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "invoice_items_insert_authenticated" ON "public"."invoice_items" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "invoice_items_select_authenticated" ON "public"."invoice_items" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "invoice_items_update_authenticated" ON "public"."invoice_items" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."invoices" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "invoices_insert_authenticated" ON "public"."invoices" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "invoices_select_authenticated" ON "public"."invoices" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "invoices_update_authenticated" ON "public"."invoices" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."leads" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "leads_insert_authenticated" ON "public"."leads" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "leads_select_authenticated" ON "public"."leads" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "leads_update_authenticated" ON "public"."leads" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."payments" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "payments_insert_authenticated" ON "public"."payments" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "payments_select_authenticated" ON "public"."payments" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "payments_update_authenticated" ON "public"."payments" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "profiles_select_own_or_admin" ON "public"."profiles" FOR SELECT TO "authenticated" USING ((("id" = "auth"."uid"()) OR "public"."is_admin"()));



CREATE POLICY "profiles_update_admin" ON "public"."profiles" FOR UPDATE TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());



ALTER TABLE "public"."quotation_items" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "quotation_items_insert_authenticated" ON "public"."quotation_items" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "quotation_items_select_authenticated" ON "public"."quotation_items" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "quotation_items_update_authenticated" ON "public"."quotation_items" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."quotations" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "quotations_insert_authenticated" ON "public"."quotations" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "quotations_select_authenticated" ON "public"."quotations" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "quotations_update_authenticated" ON "public"."quotations" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."renewals" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "renewals_insert_authenticated" ON "public"."renewals" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "renewals_select_authenticated" ON "public"."renewals" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "renewals_update_authenticated" ON "public"."renewals" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (("auth"."uid"() IS NOT NULL));



ALTER TABLE "public"."sales_persons" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "sales_persons_admin_insert" ON "public"."sales_persons" FOR INSERT TO "authenticated" WITH CHECK ("public"."is_admin"());



CREATE POLICY "sales_persons_admin_update" ON "public"."sales_persons" FOR UPDATE TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());



CREATE POLICY "sales_persons_select_authenticated" ON "public"."sales_persons" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."services" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "services_admin_insert" ON "public"."services" FOR INSERT TO "authenticated" WITH CHECK ("public"."is_admin"());



CREATE POLICY "services_admin_update" ON "public"."services" FOR UPDATE TO "authenticated" USING ("public"."is_admin"()) WITH CHECK ("public"."is_admin"());



CREATE POLICY "services_select_authenticated" ON "public"."services" FOR SELECT TO "authenticated" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."set_activity_log_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."set_activity_log_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."set_activity_log_user"() TO "service_role";


















GRANT ALL ON TABLE "public"."activity_logs" TO "anon";
GRANT ALL ON TABLE "public"."activity_logs" TO "authenticated";
GRANT ALL ON TABLE "public"."activity_logs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."activity_logs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."activity_logs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."activity_logs_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."clients" TO "anon";
GRANT ALL ON TABLE "public"."clients" TO "authenticated";
GRANT ALL ON TABLE "public"."clients" TO "service_role";



GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."clients_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."follow_ups" TO "anon";
GRANT ALL ON TABLE "public"."follow_ups" TO "authenticated";
GRANT ALL ON TABLE "public"."follow_ups" TO "service_role";



GRANT ALL ON SEQUENCE "public"."follow_ups_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."follow_ups_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."follow_ups_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."invoice_items" TO "anon";
GRANT ALL ON TABLE "public"."invoice_items" TO "authenticated";
GRANT ALL ON TABLE "public"."invoice_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."invoice_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."invoice_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."invoice_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."invoices" TO "anon";
GRANT ALL ON TABLE "public"."invoices" TO "authenticated";
GRANT ALL ON TABLE "public"."invoices" TO "service_role";



GRANT ALL ON SEQUENCE "public"."invoices_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."invoices_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."invoices_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."leads" TO "anon";
GRANT ALL ON TABLE "public"."leads" TO "authenticated";
GRANT ALL ON TABLE "public"."leads" TO "service_role";



GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."leads_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."payments" TO "anon";
GRANT ALL ON TABLE "public"."payments" TO "authenticated";
GRANT ALL ON TABLE "public"."payments" TO "service_role";



GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."payments_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON TABLE "public"."quotation_items" TO "anon";
GRANT ALL ON TABLE "public"."quotation_items" TO "authenticated";
GRANT ALL ON TABLE "public"."quotation_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quotation_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quotation_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quotation_items_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."quotations" TO "anon";
GRANT ALL ON TABLE "public"."quotations" TO "authenticated";
GRANT ALL ON TABLE "public"."quotations" TO "service_role";



GRANT ALL ON SEQUENCE "public"."quotations_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."quotations_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."quotations_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."renewals" TO "anon";
GRANT ALL ON TABLE "public"."renewals" TO "authenticated";
GRANT ALL ON TABLE "public"."renewals" TO "service_role";



GRANT ALL ON SEQUENCE "public"."renewals_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."renewals_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."renewals_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."sales_persons" TO "anon";
GRANT ALL ON TABLE "public"."sales_persons" TO "authenticated";
GRANT ALL ON TABLE "public"."sales_persons" TO "service_role";



GRANT ALL ON SEQUENCE "public"."sales_persons_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."sales_persons_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."sales_persons_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."services" TO "anon";
GRANT ALL ON TABLE "public"."services" TO "authenticated";
GRANT ALL ON TABLE "public"."services" TO "service_role";



GRANT ALL ON SEQUENCE "public"."services_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."services_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."services_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";