/* =========================================================
   INVOICE STORE
   Bharatrath CRM
   React + TypeScript
========================================================= */

import { createActivityLog } from "./activityLogStore";

/* =========================================================
   TYPES
========================================================= */

export type InvoiceStatus =
  | "Draft"
  | "Sent"
  | "Partially Paid"
  | "Paid"
  | "Overdue"
  | "Cancelled";

export type BillingFrequency = string;

/* =========================================================
   INVOICE ITEM
========================================================= */

export interface InvoiceItem {
  id: string;
  serviceId?: string;
  serviceName: string;
  description: string;
  sac: string;
  basicCost: number;
  discount: number;
  finalCost: number;
  frequency: BillingFrequency;
}

/* =========================================================
   PAYMENT
========================================================= */

export type PaymentStatus = "Active" | "Cancelled";

export interface InvoicePayment {
  id: string;
  invoiceId: string;
  paymentDate: string;
  amountPaid: number;
  paymentMode: string;
  transactionNumber?: string;
  paymentProof?: string;
  notes?: string;
  status: PaymentStatus;
  cancelledAt?: string;
  cancellationReason?: string;
}

/* =========================================================
   INVOICE
========================================================= */

export interface Invoice {
  id: string;
  invoiceNumber: string;

  clientId: string;
  clientName: string;

  clientContactPerson?: string;
  clientAddress?: string;
  clientGstNumber?: string;
  clientEmail?: string;
  clientPhone?: string;

  quotationId?: string;
  quotationNumber?: string;

  renewalId?: string;
  renewalReference?: string;

  invoiceDate: string;
  dueDate?: string;

  status: InvoiceStatus;

  items: InvoiceItem[];

  subtotal: number;
  tax: number;
  taxAmount: number;
  grandTotal: number;

  /*
   * Kept for backward compatibility with existing CRM code.
   * Current value remains subtotal.
   */
  amount: number;

  notes?: string;

  payments: InvoicePayment[];

  createdAt: string;
  updatedAt: string;
}

/* =========================================================
   CREATE INPUT
========================================================= */

export interface CreateInvoiceInput {
  /*
   * Deprecated:
   * Invoice number is generated by createInvoice().
   * Kept optional for backward compatibility so existing
   * callers do not break.
   */
  invoiceNumber?: string;

  clientId: string;
  clientName: string;

  clientContactPerson?: string;
  clientAddress?: string;
  clientGstNumber?: string;
  clientEmail?: string;
  clientPhone?: string;

  quotationId?: string;
  quotationNumber?: string;

  renewalId?: string;
  renewalReference?: string;

  invoiceDate: string;
  dueDate?: string;

  status?: InvoiceStatus;

  items: Partial<InvoiceItem>[];

  tax?: number;
  notes?: string;

  /*
   * Deprecated compatibility field.
   * Financial totals are calculated from items + tax.
   */
  amount?: number;
}

/* =========================================================
   PAYMENT INPUT
========================================================= */

export interface AddPaymentInput {
  paymentDate: string;
  amountPaid: number;
  paymentMode: string;
  transactionNumber?: string;
  paymentProof?: string;
  notes?: string;
}

/* =========================================================
   STORAGE
========================================================= */

const STORAGE_KEY = "bharatrath_crm_invoices";

/* =========================================================
   HELPERS
========================================================= */

function generateId(prefix: string): string {
  return `${prefix}-${Date.now()}-${Math.random()
    .toString(36)
    .substring(2, 8)}`;
}

function roundMoney(value: number): number {
  return Math.round((value + Number.EPSILON) * 100) / 100;
}

function invoiceRecordName(invoice: Invoice): string {
  return invoice.invoiceNumber || invoice.id;
}

/* =========================================================
   INVOICE NUMBER TYPES
========================================================= */

export type InvoiceNumberPrefix = "BDP" | "QTN" | "REN";

/* =========================================================
   INVOICE NUMBER PREFIX
========================================================= */

/*
 * Invoice numbering policy:
 *
 * Normal invoice:
 * BDP-002-2026-001
 *
 * Invoice created from quotation:
 * BDP-002-2026-002
 *
 * Renewal invoice:
 * REN-002-2026-001
 *
 * IMPORTANT:
 *
 * A quotation number is only a reference.
 * It must NOT change the invoice prefix.
 *
 * Example:
 *
 * Quotation:
 * QUO-009
 *
 * Invoice:
 * BDP-002-2026-001
 *
 * This keeps quotation numbering and invoice numbering
 * completely separate.
 */

function getInvoicePrefix(input: CreateInvoiceInput): InvoiceNumberPrefix {
  if (input.renewalId || input.renewalReference) {
    return "REN";
  }

  return "BDP";
}

/* =========================================================
   CLIENT SERIAL
========================================================= */

/*
 * CRM Client IDs:
 *
 * CL-001
 * CL-002
 * CL-003
 *
 * Invoice uses:
 *
 * 001
 * 002
 * 003
 */

function getClientSerial(clientId: string): string {
  const value = String(clientId || "").trim();

  const match = value.match(/(\d+)$/);

  if (!match) {
    return "000";
  }

  return String(Number(match[1])).padStart(3, "0");
}

/* =========================================================
   GET ALL INVOICES
========================================================= */

export function getInvoices(): Invoice[] {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);

    if (!stored) {
      return [];
    }

    const parsed: unknown = JSON.parse(stored);

    if (!Array.isArray(parsed)) {
      return [];
    }

    return (parsed as Invoice[]).map((invoice) => ({
      ...invoice,

      payments: Array.isArray(invoice.payments) ? invoice.payments : [],
    }));
  } catch (error) {
    console.error("Failed to load invoices:", error);

    return [];
  }
}

/* =========================================================
   SAVE INVOICES
========================================================= */

export function saveInvoices(invoices: Invoice[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(invoices));
}

/* =========================================================
   GENERATE INVOICE NUMBER
========================================================= */

/*
 * Final format:
 *
 * PREFIX-CLIENT-YEAR-SERIAL
 *
 * Examples:
 *
 * BDP-002-2026-001
 * BDP-002-2026-002
 * REN-002-2026-001
 */

export function generateInvoiceNumber(
  clientId: string,
  prefix: InvoiceNumberPrefix = "BDP",
  invoiceDate?: string,
): string {
  const invoices = getInvoices();

  const date = invoiceDate ? new Date(invoiceDate) : new Date();

  const year = date.getFullYear();

  const clientSerial = getClientSerial(clientId);

  const numberPrefix = `${prefix}-${clientSerial}-${year}-`;

  let highestSerial = 0;

  invoices.forEach((invoice) => {
    const invoiceNumber = String(invoice.invoiceNumber || "").trim();

    if (!invoiceNumber.startsWith(numberPrefix)) {
      return;
    }

    const parts = invoiceNumber.split("-");

    if (parts.length !== 4) {
      return;
    }

    const serial = Number(parts[3]);

    if (!Number.isNaN(serial)) {
      highestSerial = Math.max(highestSerial, serial);
    }
  });

  return `${numberPrefix}${String(highestSerial + 1).padStart(3, "0")}`;
}

/* =========================================================
   GET SINGLE INVOICE
========================================================= */

export function getInvoiceById(invoiceId: string): Invoice | undefined {
  const invoices = getInvoices();

  return invoices.find((invoice) => invoice.id === invoiceId);
}

/* =========================================================
   GET SINGLE INVOICE
   ALIAS
========================================================= */

export function getInvoice(invoiceId: string): Invoice | undefined {
  return getInvoiceById(invoiceId);
}

/* =========================================================
   GET SINGLE INVOICE BY RENEWAL
========================================================= */

export function getInvoiceByRenewalId(renewalId: string): Invoice | undefined {
  const invoices = getInvoices();

  return invoices.find((invoice) => invoice.renewalId === renewalId);
}

/* =========================================================
   GET INVOICE BY QUOTATION ID
========================================================= */

export function getInvoiceByQuotationId(
  quotationId: string,
): Invoice | undefined {
  const normalizedQuotationId = String(quotationId || "").trim();

  if (!normalizedQuotationId) {
    return undefined;
  }

  const invoices = getInvoices();

  return invoices.find(
    (invoice) =>
      String(invoice.quotationId || "").trim() === normalizedQuotationId,
  );
}

/* =========================================================
   GET INVOICE BY QUOTATION NUMBER
========================================================= */

export function getInvoiceByQuotationNumber(
  quotationNumber: string,
): Invoice | undefined {
  const normalizedQuotationNumber = String(quotationNumber || "").trim();

  if (!normalizedQuotationNumber) {
    return undefined;
  }

  const invoices = getInvoices();

  return invoices.find(
    (invoice) =>
      String(invoice.quotationNumber || "").trim() ===
      normalizedQuotationNumber,
  );
}

/* =========================================================
   GET INVOICE BY QUOTATION REFERENCE
========================================================= */

export function getInvoiceByQuotationReference(
  quotationId?: string,
  quotationNumber?: string,
): Invoice | undefined {
  if (quotationId) {
    const invoiceById = getInvoiceByQuotationId(quotationId);

    if (invoiceById) {
      return invoiceById;
    }
  }

  if (quotationNumber) {
    const invoiceByNumber = getInvoiceByQuotationNumber(quotationNumber);

    if (invoiceByNumber) {
      return invoiceByNumber;
    }
  }

  return undefined;
}

/* =========================================================
   GENERATE INTERNAL INVOICE ID
========================================================= */

export function generateInvoiceId(): string {
  const invoices = getInvoices();

  let highest = 0;

  invoices.forEach((invoice) => {
    const match = String(invoice.id).match(/^INV-(\d+)$/);

    if (!match) {
      return;
    }

    const number = Number(match[1]);

    if (number > highest) {
      highest = number;
    }
  });

  return `INV-${String(highest + 1).padStart(3, "0")}`;
}

/* =========================================================
   CALCULATE ITEM
========================================================= */

export function calculateItem(item: Partial<InvoiceItem>): InvoiceItem {
  const basicCost = Math.max(0, Number(item.basicCost) || 0);

  const discount = Math.min(basicCost, Math.max(0, Number(item.discount) || 0));

  const finalCost = Math.max(0, basicCost - discount);

  return {
    id: item.id || generateId("ITEM"),

    serviceId: item.serviceId,

    serviceName: item.serviceName || item.description || "",

    description: item.description || item.serviceName || "",

    sac: item.sac || "",

    basicCost: roundMoney(basicCost),

    discount: roundMoney(discount),

    finalCost: roundMoney(finalCost),

    frequency: item.frequency || "",
  };
}

/* =========================================================
   CALCULATE TOTALS
========================================================= */

export interface InvoiceTotals {
  subtotal: number;
  tax: number;
  taxAmount: number;
  grandTotal: number;
}

export function calculateInvoiceTotals(
  items: InvoiceItem[],
  taxPercent: number,
): InvoiceTotals {
  const subtotal = roundMoney(
    items.reduce(
      (total: number, item: InvoiceItem) =>
        total + (Number(item.finalCost) || 0),
      0,
    ),
  );

  const tax = Math.max(0, Number(taxPercent) || 0);

  const taxAmount = roundMoney((subtotal * tax) / 100);

  const grandTotal = roundMoney(subtotal + taxAmount);

  return {
    subtotal,
    tax,
    taxAmount,
    grandTotal,
  };
}

/* =========================================================
   CREATE INVOICE
========================================================= */

/*
 * IMPORTANT:
 *
 * createInvoice() is the single source of truth
 * for invoice number generation.
 *
 * Caller-provided invoiceNumber is intentionally ignored.
 *
 * This prevents UI components from accidentally creating
 * duplicate or incorrectly prefixed invoice numbers.
 */

export function createInvoice(input: CreateInvoiceInput): Invoice {
  /*
   * A quotation can generate only ONE invoice.
   *
   * Check both quotationId and quotationNumber so that
   * old/legacy invoice records are also protected.
   *
   * Cancelled invoices are intentionally included.
   */
  const existingQuotationInvoice = getInvoiceByQuotationReference(
    input.quotationId,
    input.quotationNumber,
  );

  if (existingQuotationInvoice) {
    throw new Error(
      `An invoice already exists for quotation "${existingQuotationInvoice.quotationNumber || input.quotationNumber || input.quotationId}".`,
    );
  }

  const now = new Date().toISOString();

  const items = input.items
    .map((item) => calculateItem(item))
    .filter((item) => item.serviceName.trim() !== "");

  const totals = calculateInvoiceTotals(items, input.tax ?? 18);

  const prefix = getInvoicePrefix(input);

  const invoiceNumber = generateInvoiceNumber(
    input.clientId,
    prefix,
    input.invoiceDate,
  );

  const invoice: Invoice = {
    id: generateInvoiceId(),

    invoiceNumber,

    clientId: input.clientId,

    clientName: input.clientName,

    clientContactPerson: input.clientContactPerson,

    clientAddress: input.clientAddress,

    clientGstNumber: input.clientGstNumber,

    clientEmail: input.clientEmail,

    clientPhone: input.clientPhone,

    quotationId: input.quotationId || undefined,

    quotationNumber: input.quotationNumber || undefined,

    renewalId: input.renewalId || undefined,

    renewalReference: input.renewalReference || undefined,

    invoiceDate: input.invoiceDate,

    dueDate: input.dueDate || undefined,

    status: input.status || "Draft",

    items,

    subtotal: totals.subtotal,

    tax: totals.tax,

    taxAmount: totals.taxAmount,

    grandTotal: totals.grandTotal,

    /*
     * Existing CRM compatibility.
     */
    amount: totals.subtotal,

    notes: input.notes || "",

    payments: [],

    createdAt: now,

    updatedAt: now,
  };

  const invoices = getInvoices();

  invoices.push(invoice);

  saveInvoices(invoices);

  /* =======================================================
     ACTIVITY: INVOICE CREATED
  ======================================================= */

  void createActivityLog({
    action: "INVOICE_CREATED",

    module: "Invoices",

    record_id: invoice.id,

    record_name: invoiceRecordName(invoice),

    description: `Created invoice "${invoice.invoiceNumber}" for "${invoice.clientName}"`,

    new_data: invoice as unknown as Record<string, unknown>,
  });

  return invoice;
}

/* =========================================================
   ADD INVOICE
========================================================= */

/*
 * Legacy/direct insert function.
 *
 * Kept for compatibility with existing code.
 *
 * New invoice creation should preferably use
 * createInvoice() because it guarantees numbering.
 */

export function addInvoice(invoice: Invoice): Invoice {
  const invoices = getInvoices();

  invoices.push({
    ...invoice,

    payments: Array.isArray(invoice.payments) ? invoice.payments : [],
  });

  saveInvoices(invoices);

  /* =======================================================
     ACTIVITY: INVOICE CREATED
  ======================================================= */

  void createActivityLog({
    action: "INVOICE_CREATED",

    module: "Invoices",

    record_id: invoice.id,

    record_name: invoiceRecordName(invoice),

    description: `Created invoice "${invoice.invoiceNumber}" for "${invoice.clientName}"`,

    new_data: invoice as unknown as Record<string, unknown>,
  });

  return invoice;
}

/* =========================================================
   UPDATE INVOICE
========================================================= */

export function updateInvoice(
  invoiceId: string,
  updates: Partial<Invoice>,
): Invoice | undefined {
  const invoices = getInvoices();

  const index = invoices.findIndex((invoice) => invoice.id === invoiceId);

  if (index === -1) {
    return undefined;
  }

  const existing = invoices[index];

  /*
   * Cancelled invoices are historical records.
   *
   * They cannot be restored or changed through the
   * normal update flow.
   */
  if (existing.status === "Cancelled" && updates.status !== "Cancelled") {
    return existing;
  }

  /*
   * Invoice number is immutable.
   *
   * Even if a UI accidentally sends invoiceNumber,
   * the original number remains unchanged.
   */
  const {
    invoiceNumber: _ignoredInvoiceNumber,
    id: _ignoredId,
    createdAt: _ignoredCreatedAt,
    ...safeUpdates
  } = updates;

  void _ignoredInvoiceNumber;
  void _ignoredId;
  void _ignoredCreatedAt;

  const updatedBase: Invoice = {
    ...existing,

    ...safeUpdates,

    id: existing.id,

    invoiceNumber: existing.invoiceNumber,

    createdAt: existing.createdAt,

    updatedAt: new Date().toISOString(),
  };

  let updated: Invoice = updatedBase;

  /* =======================================================
     RECALCULATE FINANCIAL TOTALS
  ======================================================= */

  if (updates.items !== undefined || updates.tax !== undefined) {
    const sourceItems = updates.items ?? existing.items;

    const items = sourceItems.map((item) => calculateItem(item));

    const tax = updates.tax ?? existing.tax;

    const totals = calculateInvoiceTotals(items, tax);

    updated = {
      ...updatedBase,

      items,

      subtotal: totals.subtotal,

      tax: totals.tax,

      taxAmount: totals.taxAmount,

      grandTotal: totals.grandTotal,

      amount: totals.subtotal,
    };
  }

  invoices[index] = updated;

  saveInvoices(invoices);

  const oldData = existing as unknown as Record<string, unknown>;

  const newData = updated as unknown as Record<string, unknown>;

  /* =======================================================
     ACTIVITY: STATUS CHANGED
  ======================================================= */

  if (existing.status !== updated.status) {
    void createActivityLog({
      action: "STATUS_CHANGED",

      module: "Invoices",

      record_id: updated.id,

      record_name: invoiceRecordName(updated),

      description: `Changed invoice "${updated.invoiceNumber}" status from "${existing.status}" to "${updated.status}"`,

      old_data: oldData,

      new_data: newData,
    });
  }

  /* =======================================================
     ACTIVITY: GENERAL UPDATE
  ======================================================= */

  const updateKeys = Object.keys(safeUpdates).filter((key) => key !== "status");

  if (updateKeys.length > 0) {
    void createActivityLog({
      action: "UPDATE",

      module: "Invoices",

      record_id: updated.id,

      record_name: invoiceRecordName(updated),

      description: `Updated invoice "${updated.invoiceNumber}"`,

      old_data: oldData,

      new_data: newData,
    });
  }

  return updated;
}

/* =========================================================
   DELETE / ARCHIVE INVOICE
========================================================= */

/*
 * IMPORTANT:
 *
 * Invoice is NEVER physically deleted.
 *
 * deleteInvoice() changes status to Cancelled and
 * preserves the complete record.
 */

export function deleteInvoice(invoiceId: string): boolean {
  const invoices = getInvoices();

  const index = invoices.findIndex((invoice) => invoice.id === invoiceId);

  if (index === -1) {
    return false;
  }

  const invoice = invoices[index];

  if (invoice.status === "Cancelled") {
    return true;
  }

  const updatedInvoice: Invoice = {
    ...invoice,

    status: "Cancelled",

    updatedAt: new Date().toISOString(),
  };

  invoices[index] = updatedInvoice;

  saveInvoices(invoices);

  /* =======================================================
     ACTIVITY: INVOICE ARCHIVED/CANCELLED
  ======================================================= */

  void createActivityLog({
    action: "ARCHIVE",

    module: "Invoices",

    record_id: updatedInvoice.id,

    record_name: invoiceRecordName(updatedInvoice),

    description: `Cancelled invoice "${updatedInvoice.invoiceNumber}"`,

    old_data: invoice as unknown as Record<string, unknown>,

    new_data: updatedInvoice as unknown as Record<string, unknown>,
  });

  return true;
}

/* =========================================================
   DUPLICATE INVOICE
========================================================= */

/*
 * Duplicate always creates a NEW invoice.
 *
 * Therefore:
 *
 * - New internal ID
 * - New invoice number
 * - Draft status
 *
 * Original invoice remains untouched.
 */

export function duplicateInvoice(invoiceId: string): Invoice | undefined {
  const invoice = getInvoiceById(invoiceId);

  if (!invoice) {
    return undefined;
  }

  return createInvoice({
    clientId: invoice.clientId,

    clientName: invoice.clientName,

    clientContactPerson: invoice.clientContactPerson,

    clientAddress: invoice.clientAddress,

    clientGstNumber: invoice.clientGstNumber,

    clientEmail: invoice.clientEmail,

    clientPhone: invoice.clientPhone,

    /*
     * A duplicated invoice is a new independent invoice.
     * Do not carry the original quotation reference,
     * otherwise the one-invoice-per-quotation protection
     * would correctly reject the duplicate.
     */
    quotationId: undefined,

    quotationNumber: undefined,

    renewalId: undefined,

    renewalReference: undefined,

    invoiceDate: new Date().toISOString().split("T")[0],

    dueDate: invoice.dueDate,

    status: "Draft",

    items: invoice.items.map((item) => ({
      ...item,
      id: undefined,
    })),

    tax: invoice.tax,

    notes: invoice.notes,
  });
}

/* =========================================================
   ADD PAYMENT
========================================================= */

export function addInvoicePayment(
  invoiceId: string,
  input: AddPaymentInput,
): Invoice | undefined {
  const invoices = getInvoices();

  const index = invoices.findIndex((invoice) => invoice.id === invoiceId);

  if (index === -1) {
    return undefined;
  }

  const invoice = invoices[index];

  if (invoice.status === "Cancelled") {
    throw new Error("Payment cannot be added to a cancelled invoice.");
  }

  const paymentAmount = roundMoney(Number(input.amountPaid) || 0);

  if (paymentAmount <= 0) {
    throw new Error("Payment amount must be greater than zero.");
  }

  if (
    !input.paymentDate ||
    Number.isNaN(new Date(`${input.paymentDate}T00:00:00`).getTime())
  ) {
    throw new Error("Payment date is required and must be valid.");
  }

  if (!input.paymentMode?.trim()) {
    throw new Error("Payment mode is required.");
  }

  const payments = Array.isArray(invoice.payments) ? invoice.payments : [];

  const totalPaid = roundMoney(
    payments
      .filter((payment) => payment.status !== "Cancelled")
      .reduce((total, payment) => total + Number(payment.amountPaid || 0), 0),
  );

  const grandTotal = roundMoney(Number(invoice.grandTotal) || 0);

  if (grandTotal <= 0) {
    throw new Error("Invoice total must be greater than zero.");
  }

  const balance = roundMoney(grandTotal - totalPaid);

  if (balance <= 0) {
    throw new Error("This invoice is already fully paid.");
  }

  if (paymentAmount > balance) {
    throw new Error("Payment cannot be greater than outstanding balance.");
  }

  const payment: InvoicePayment = {
    id: generateId("PAY"),

    invoiceId,

    paymentDate: input.paymentDate,

    amountPaid: paymentAmount,

    paymentMode: input.paymentMode,

    transactionNumber: input.transactionNumber || "",

    paymentProof: input.paymentProof || "",

    notes: input.notes || "",

    status: "Active",
  };

  invoice.payments = [...payments, payment];

  const newTotalPaid = roundMoney(
    invoice.payments
      .filter((item) => item.status !== "Cancelled")
      .reduce((total, item) => total + Number(item.amountPaid || 0), 0),
  );

  /* =======================================================
     UPDATE INVOICE STATUS
  ======================================================= */

  if (newTotalPaid >= invoice.grandTotal) {
    invoice.status = "Paid";
  } else if (newTotalPaid > 0) {
    invoice.status = "Partially Paid";
  } else {
    invoice.status =
      invoice.dueDate && new Date(invoice.dueDate) < new Date()
        ? "Overdue"
        : "Sent";
  }

  invoice.updatedAt = new Date().toISOString();

  invoices[index] = invoice;

  saveInvoices(invoices);

  /* =======================================================
     ACTIVITY: PAYMENT ADDED
  ======================================================= */

  void createActivityLog({
    action: "PAYMENT_ADDED",

    module: "Payments",

    record_id: invoice.invoiceNumber,

    record_name: invoice.clientName,

    description: `Added payment of ₹${paymentAmount.toLocaleString(
      "en-IN",
    )} to invoice ${invoice.invoiceNumber}`,

    new_data: {
      paymentId: payment.id,

      invoiceId: invoice.id,

      invoiceNumber: invoice.invoiceNumber,

      clientName: invoice.clientName,

      amountPaid: paymentAmount,

      paymentMode: payment.paymentMode,

      paymentDate: payment.paymentDate,

      transactionNumber: payment.transactionNumber || "",

      totalPaid: newTotalPaid,

      outstandingBalance: Math.max(
        0,
        roundMoney(invoice.grandTotal - newTotalPaid),
      ),

      invoiceStatus: invoice.status,
    },
  });

  return invoice;
}

/* =========================================================
   CANCEL PAYMENT
   Payment remains permanently in history.
========================================================= */

export function cancelInvoicePayment(
  invoiceId: string,
  paymentId: string,
  cancellationReason: string = "Payment cancelled",
): Invoice | undefined {
  const invoices = getInvoices();

  const index = invoices.findIndex((invoice) => invoice.id === invoiceId);

  if (index === -1) {
    return undefined;
  }

  const invoice = invoices[index];

  if (!Array.isArray(invoice.payments)) {
    invoice.payments = [];
  }

  const paymentIndex = invoice.payments.findIndex(
    (payment) => payment.id === paymentId,
  );

  if (paymentIndex === -1) {
    return undefined;
  }

  const payment = invoice.payments[paymentIndex];

  if (payment.status === "Cancelled") {
    return invoice;
  }

  const reason = cancellationReason.trim() || "Payment cancelled";

  const cancelledAt = new Date().toISOString();

  invoice.payments[paymentIndex] = {
    ...payment,

    status: "Cancelled",

    cancelledAt,

    cancellationReason: reason,
  };

  /* =======================================================
     RECALCULATE ACTIVE PAYMENTS
  ======================================================= */

  const activePayments = invoice.payments.filter(
    (item) => item.status !== "Cancelled",
  );

  const totalPaid = roundMoney(
    activePayments.reduce(
      (total, item) => total + Number(item.amountPaid || 0),
      0,
    ),
  );

  /* =======================================================
     UPDATE INVOICE STATUS
  ======================================================= */

  if (totalPaid <= 0) {
    if (
      invoice.status === "Paid" ||
      invoice.status === "Partially Paid" ||
      invoice.status === "Overdue"
    ) {
      invoice.status =
        invoice.dueDate && new Date(invoice.dueDate) < new Date()
          ? "Overdue"
          : "Sent";
    }
  } else if (totalPaid >= invoice.grandTotal) {
    invoice.status = "Paid";
  } else {
    invoice.status = "Partially Paid";
  }

  invoice.updatedAt = cancelledAt;

  invoices[index] = invoice;

  saveInvoices(invoices);

  /* =======================================================
     ACTIVITY: PAYMENT CANCELLED
  ======================================================= */

  void createActivityLog({
    action: "PAYMENT_CANCELLED",

    module: "Payments",

    record_id: invoice.invoiceNumber,

    record_name: invoice.clientName,

    description: `Cancelled payment of ₹${Number(
      payment.amountPaid || 0,
    ).toLocaleString("en-IN")} for invoice ${invoice.invoiceNumber}`,

    old_data: {
      paymentId: payment.id,

      invoiceId: invoice.id,

      invoiceNumber: invoice.invoiceNumber,

      clientName: invoice.clientName,

      amountPaid: payment.amountPaid,

      paymentMode: payment.paymentMode,

      paymentDate: payment.paymentDate,

      status: "Active",
    },

    new_data: {
      paymentId: payment.id,

      status: "Cancelled",

      cancellationReason: reason,

      cancelledAt,

      totalPaid,

      outstandingBalance: Math.max(
        0,
        roundMoney(invoice.grandTotal - totalPaid),
      ),

      invoiceStatus: invoice.status,
    },
  });

  return invoice;
}

/* =========================================================
   LEGACY PAYMENT FUNCTION
========================================================= */

/*
 * Kept for backward compatibility.
 *
 * It does NOT physically remove payment.
 */

export function removeInvoicePayment(
  invoiceId: string,
  paymentId: string,
): Invoice | undefined {
  return cancelInvoicePayment(invoiceId, paymentId, "Payment cancelled");
}

/* =========================================================
   PAYMENT SUMMARY
========================================================= */

export interface InvoicePaymentSummary {
  totalPaid: number;
  balance: number;
  isPaid: boolean;
}

export function getInvoicePaymentSummary(
  invoice: Invoice,
): InvoicePaymentSummary {
  const activePayments = Array.isArray(invoice.payments)
    ? invoice.payments.filter((payment) => payment.status !== "Cancelled")
    : [];

  const totalPaid = roundMoney(
    activePayments.reduce(
      (total, payment) => total + Number(payment.amountPaid || 0),
      0,
    ),
  );

  const balance = Math.max(0, roundMoney(invoice.grandTotal - totalPaid));

  return {
    totalPaid,

    balance,

    isPaid: balance <= 0,
  };
}

/* =========================================================
   SEARCH INVOICES
========================================================= */

export function searchInvoices(
  searchTerm: string,
  status: InvoiceStatus | "All" = "All",
): Invoice[] {
  const invoices = getInvoices();

  const search = searchTerm.trim().toLowerCase();

  return invoices.filter((invoice) => {
    const matchesSearch =
      !search ||
      invoice.invoiceNumber.toLowerCase().includes(search) ||
      invoice.clientName.toLowerCase().includes(search) ||
      invoice.items.some((item) =>
        item.serviceName.toLowerCase().includes(search),
      );

    const matchesStatus = status === "All" || invoice.status === status;

    return matchesSearch && matchesStatus;
  });
}

/* =========================================================
   SORT INVOICES
========================================================= */

export function getInvoicesSorted(): Invoice[] {
  return [...getInvoices()].sort(
    (a, b) =>
      new Date(b.invoiceDate).getTime() - new Date(a.invoiceDate).getTime(),
  );
}

/* =========================================================
   INVOICE SUMMARY
========================================================= */

export interface InvoiceSummary {
  total: number;
  draft: number;
  sent: number;

  /*
   * Kept for backward compatibility.
   *
   * Existing UI may still use this field.
   * It currently represents Paid invoices.
   */
  accepted: number;

  totalValue: number;
  totalPaid: number;
  outstanding: number;
}

export function getInvoiceSummary(): InvoiceSummary {
  const invoices = getInvoices();

  const activeInvoices = invoices.filter(
    (invoice) => invoice.status !== "Cancelled",
  );

  /*
   * Total includes historical/cancelled invoices
   * for compatibility with the existing summary behavior.
   */
  const total = invoices.length;

  const draft = activeInvoices.filter(
    (invoice) => invoice.status === "Draft",
  ).length;

  const sent = activeInvoices.filter(
    (invoice) => invoice.status === "Sent",
  ).length;

  /*
   * Existing API field "accepted" is preserved.
   *
   * Invoice statuses do not have "Accepted".
   * Therefore this currently counts Paid invoices.
   */
  const accepted = activeInvoices.filter(
    (invoice) => invoice.status === "Paid",
  ).length;

  const totalValue = roundMoney(
    activeInvoices.reduce(
      (sum, invoice) => sum + Number(invoice.grandTotal || 0),
      0,
    ),
  );

  const totalPaid = roundMoney(
    activeInvoices.reduce(
      (sum, invoice) =>
        sum +
        (Array.isArray(invoice.payments)
          ? invoice.payments
              .filter((payment) => payment.status !== "Cancelled")
              .reduce(
                (paymentTotal, payment) =>
                  paymentTotal + Number(payment.amountPaid || 0),
                0,
              )
          : 0),
      0,
    ),
  );

  const outstanding = Math.max(0, roundMoney(totalValue - totalPaid));

  return {
    total,

    draft,

    sent,

    accepted,

    totalValue,

    totalPaid,

    outstanding,
  };
}

/* =========================================================
   UPDATE OVERDUE INVOICES
========================================================= */

export function updateOverdueInvoices(): void {
  const invoices = getInvoices();

  const today = new Date();

  today.setHours(0, 0, 0, 0);

  let changed = false;

  invoices.forEach((invoice) => {
    /*
     * Paid and cancelled invoices are never marked overdue.
     */
    if (invoice.status === "Paid" || invoice.status === "Cancelled") {
      return;
    }

    if (!invoice.dueDate) {
      return;
    }

    const dueDate = new Date(invoice.dueDate);

    dueDate.setHours(0, 0, 0, 0);

    if (dueDate < today) {
      const paymentSummary = getInvoicePaymentSummary(invoice);

      if (!paymentSummary.isPaid) {
        if (invoice.status !== "Overdue") {
          invoice.status = "Overdue";

          invoice.updatedAt = new Date().toISOString();

          changed = true;
        }
      }
    }
  });

  if (changed) {
    saveInvoices(invoices);
  }
}

/* =========================================================
   CLEAR / ARCHIVE ALL INVOICES
========================================================= */

/*
 * IMPORTANT:
 *
 * The old implementation:
 *
 * localStorage.removeItem(STORAGE_KEY)
 *
 * permanently destroyed all invoice history.
 *
 * Bharatrath CRM should retain financial history.
 *
 * Therefore this function is retained only for backward
 * compatibility, but it now CANCELS/ARCHIVES all invoices
 * instead of permanently deleting them.
 *
 * Existing invoice IDs, numbers, payments and history remain.
 */

export function clearAllInvoices(): void {
  const invoices = getInvoices();

  if (invoices.length === 0) {
    return;
  }

  const now = new Date().toISOString();

  let changed = false;

  const archivedInvoices = invoices.map((invoice) => {
    if (invoice.status === "Cancelled") {
      return invoice;
    }

    changed = true;

    return {
      ...invoice,

      status: "Cancelled" as InvoiceStatus,

      updatedAt: now,
    };
  });

  if (changed) {
    saveInvoices(archivedInvoices);
  }
}
